version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_inventory
    restart: always
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_inventory
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventorydb
      - SPRING_DATASOURCE_USERNAME=inventoryuser
      - SPRING_DATASOURCE_PASSWORD=inventorypass
    restart: on-failure

volumes:
  postgres_data:
